//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleTextEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimpleTextEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap AboutBoxBackground {
            get {
                object obj = ResourceManager.GetObject("AboutBoxBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About {0}.
        /// </summary>
        internal static string AboutText {
            get {
                return ResourceManager.GetString("AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} may need administrator privileges to register itself as a text editor. Please allow the application to make these changes..
        /// </summary>
        internal static string AdminPrivilegesNeeded {
            get {
                return ResourceManager.GetString("AdminPrivilegesNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention.
        /// </summary>
        internal static string AttentionMessageTitle {
            get {
                return ResourceManager.GetString("AttentionMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reached the end of the document.
        ///Do you want to continue from the beginning?.
        /// </summary>
        internal static string EndOfDocumentPrompt {
            get {
                return ResourceManager.GetString("EndOfDocumentPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reached the end of the selected area.
        ///Do you want to expand the search to the rest of the document?.
        /// </summary>
        internal static string EndOfSelectedAreaPrompt {
            get {
                return ResourceManager.GetString("EndOfSelectedAreaPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reached the end of the selection.
        ///Do you want to continue from the beginning?.
        /// </summary>
        internal static string EndOfSelectionPrompt {
            get {
                return ResourceManager.GetString("EndOfSelectionPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error opening &apos;{0}&apos;: {1}
        ///.
        /// </summary>
        internal static string ErrorOpeningMessage {
            get {
                return ResourceManager.GetString("ErrorOpeningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving &apos;{0}&apos;: {1}
        ///.
        /// </summary>
        internal static string ErrorSavingMessage {
            get {
                return ResourceManager.GetString("ErrorSavingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} Actions..
        /// </summary>
        internal static string HistoryBoxLabel {
            get {
                return ResourceManager.GetString("HistoryBoxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ln. {0} Col. {1}.
        /// </summary>
        internal static string LineColumnStatusbar {
            get {
                return ResourceManager.GetString("LineColumnStatusbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The text has been modified. Do you want to save before continuing?.
        /// </summary>
        internal static string ModifiedSavePrompt {
            get {
                return ResourceManager.GetString("ModifiedSavePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace All finished. Replaced {0} matches..
        /// </summary>
        internal static string ReplaceAllFinishedMessage {
            get {
                return ResourceManager.GetString("ReplaceAllFinishedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search &amp; Replace.
        /// </summary>
        internal static string SearchReplaceTitle {
            get {
                return ResourceManager.GetString("SearchReplaceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to untitled.
        /// </summary>
        internal static string UntitledDocumentTitlebarText {
            get {
                return ResourceManager.GetString("UntitledDocumentTitlebarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        internal static string VersionText {
            get {
                return ResourceManager.GetString("VersionText", resourceCulture);
            }
        }
    }
}
